spark.jars.packages=org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.3,com.google.cloud.hosted.kafka:managed-kafka-auth-login-handler:1.0.6
spark.jars.repositories=https://packages.confluent.io/maven/
spark.jars.excludes=com.google.http-client:google-http-client
